version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1984
      POSTGRES_DB: reception
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  #data saved outside the container 
volumes:
  pgdata:
